#!/bin/bash

# Test script to add Jira MCP to project-management project
# This simulates what our web interface would do

PROJECT_PATH="/Users/danielbeach/code/Work/project-management"

echo "Testing Jira MCP addition to project-management project..."
echo "Project path: $PROJECT_PATH"

# Test environment variables (replace with real values)
export JIRA_URL="https://example.atlassian.net"
export JIRA_USERNAME="test@example.com" 
export JIRA_API_TOKEN="test_token_placeholder"

echo "Environment variables set:"
echo "JIRA_URL: $JIRA_URL"
echo "JIRA_USERNAME: $JIRA_USERNAME"
echo "JIRA_API_TOKEN: [MASKED]"

# Change to project directory
cd "$PROJECT_PATH" || { echo "Error: Could not cd to project path"; exit 1; }

echo "Current directory: $(pwd)"

# Add Jira MCP to the project using Claude CLI
# This mirrors the command that would be generated by our MCPService
echo "Adding Jira MCP using Claude CLI..."

claude mcp add --scope project \
  -e JIRA_URL="$JIRA_URL" \
  -e JIRA_USERNAME="$JIRA_USERNAME" \
  -e JIRA_API_TOKEN="$JIRA_API_TOKEN" \
  jira -- docker run -i --rm \
  -e JIRA_URL \
  -e JIRA_USERNAME \
  -e JIRA_API_TOKEN \
  ghcr.io/sooperset/mcp-atlassian:latest

echo "Command completed with exit code: $?"